# Generated by Django 4.2.24 on 2025-09-05 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['id'], 'verbose_name_plural': 'Categories'},
        ),
    ]
