# Generated by Django 4.2.24 on 2025-09-05 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_coupons'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupons',
            options={'ordering': ['id'], 'verbose_name_plural': 'Coupons'},
        ),
    ]
