# Generated by Django 4.2.24 on 2025-09-05 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_role_rename_is_active_categories_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Role',
            new_name='Roles',
        ),
    ]
