# Generated by Django 4.2.24 on 2025-09-05 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_email_verified',
            new_name='email_verified',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='is_phone_verified',
            new_name='phone_verified',
        ),
    ]
