# Generated by Django 4.2.24 on 2025-09-05 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
    ]
