# Generated by Django 4.2.24 on 2025-09-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_products_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='menu',
            field=models.BooleanField(default=False),
        ),
    ]
