# Generated by Django 4.2.24 on 2025-09-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_products_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='stock',
            new_name='order',
        ),
        migrations.AddField(
            model_name='products',
            name='featured',
            field=models.BooleanField(default=True),
        ),
    ]
