# Generated by Django 4.2.24 on 2025-10-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_banner_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='type',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
