# Generated by Django 4.2.24 on 2025-10-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_slide_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='type',
            field=models.CharField(choices=[('default', 'Default'), ('image', 'Image'), ('video', 'Video')], default='default', max_length=255),
        ),
    ]
