# Generated by Django 4.2.24 on 2025-11-04 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_slide_video_alter_slide_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slide',
            old_name='type',
            new_name='slide_type',
        ),
    ]
