# Generated by Django 4.2.24 on 2025-11-04 16:14

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_rename_type_slide_slide_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.Slide.get_unique_filename),
        ),
        migrations.AlterField(
            model_name='slide',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=store.models.Slide.get_unique_filename),
        ),
    ]
