# Generated by Django 4.2.24 on 2025-11-04 16:22

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_slide_image_alter_slide_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.Slide.get_unique_filename, validators=[store.models.Slide.validate_image_size]),
        ),
    ]
